# Generated by Django 3.1.7 on 2021-06-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(choices=[('N', 'no toppings!'), ('CSp', 'coloured sprinkles'), ('ChSp', 'chocolate sprinkles'), ('Ch', 'cherries'), ('Nu', 'nuts'), ('Ca', 'caramel')], default='N', max_length=4)),
                ('quantity', models.CharField(max_length=30, verbose_name='Recommended quantity')),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.flavour')),
            ],
        ),
    ]
